openapi: 3.0.1
info:
  title: Complex Demo API
  version: 2026-01-20
  description: |
    A synthetic spec meant for testing doc renderers (navigation, schemas, auth, try-it, samples).
    Includes polymorphism, callbacks, uploads, pagination, and mixed security.
  termsOfService: https://example.com/terms
  contact:
    name: API Support
    email: api-support@example.com
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

externalDocs:
  description: Project docs
  url: https://example.com/docs

servers:
  - url: https://{region}.api.example.com/{basePath}
    description: Regional gateway
    variables:
      region:
        default: eu
        enum: [eu, us, apac]
      basePath:
        default: v1
  - url: https://sandbox.api.example.com/v1
    description: Sandbox

tags:
  - name: Payments
    description: Payment lifecycle operations
  - name: Files
    description: Upload and download files
  - name: Webhooks
    description: Webhook management
  - name: Admin
    description: Admin-only operations

# Global security: by default, endpoints require a bearer token.
security:
  - bearerAuth: []

paths:
  /health:
    get:
      summary: Health check (no auth)
      description: Public endpoint; useful to validate "operation security overrides global security".
      security: []
      tags: [Admin]
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: ok

  /payments:
    post:
      summary: Create a payment
      tags: [Payments]
      operationId: createPayment
      description: Creates a payment intent and returns its current state.
      parameters:
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePaymentRequest"
            examples:
              card:
                summary: Card payment
                value:
                  amount: 1999
                  currency: EUR
                  merchantReference: ORDER-10001
                  paymentMethod:
                    type: card
                    card:
                      token: tok_test_visa_123
                  customer:
                    id: cus_abc123
                    email: customer@example.com
                  returnUrl: https://merchant.example.com/return
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CreatePaymentForm"
      callbacks:
        paymentEvents:
          "{$request.body#/webhookUrl}":
            post:
              summary: Payment event callback
              description: |
                The server sends asynchronous events to the provided webhookUrl.
              tags: [Webhooks]
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/WebhookEvent"
              responses:
                "200":
                  description: Acknowledge event
      responses:
        "201":
          description: Payment created
          headers:
            Location:
              description: URL of created resource
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
          links:
            GetPayment:
              operationId: getPayment
              parameters:
                paymentId: "$response.body#/id"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
        "500":
          $ref: "#/components/responses/ServerError"

    get:
      summary: List payments (paginated)
      tags: [Payments]
      operationId: listPayments
      parameters:
        - $ref: "#/components/parameters/PageSize"
        - $ref: "#/components/parameters/PageCursor"
        - name: status
          in: query
          schema:
            $ref: "#/components/schemas/PaymentStatus"
      responses:
        "200":
          description: Page of payments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedPayments"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /payments/{paymentId}:
    get:
      summary: Get payment by id
      tags: [Payments]
      operationId: getPayment
      parameters:
        - $ref: "#/components/parameters/PaymentId"
      responses:
        "200":
          description: Payment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        "404":
          $ref: "#/components/responses/NotFound"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /payments/{paymentId}/capture:
    post:
      summary: Capture an authorized payment
      tags: [Payments]
      operationId: capturePayment
      parameters:
        - $ref: "#/components/parameters/PaymentId"
      # Override: allow either bearer OR apiKey OR oauth2 for this operation
      security:
        - bearerAuth: []
        - apiKeyAuth: []
        - oauth2AuthCode:
            - payments:write
      responses:
        "200":
          description: Captured
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        "409":
          description: Invalid state transition
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                code: INVALID_STATE
                message: Cannot capture a payment in state "succeeded"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /files:
    post:
      summary: Upload a file (multipart)
      tags: [Files]
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/FileUploadRequest"
      responses:
        "201":
          description: Uploaded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileObject"
        "413":
          description: Payload too large
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /files/{fileId}:
    get:
      summary: Download a file (binary)
      tags: [Files]
      operationId: downloadFile
      parameters:
        - $ref: "#/components/parameters/FileId"
      responses:
        "200":
          description: Binary content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          $ref: "#/components/responses/NotFound"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    oauth2AuthCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            payments:write: Create/capture payments
            payments:read: Read payments

  parameters:
    PaymentId:
      name: paymentId
      in: path
      required: true
      schema:
        type: string
      example: pay_123
    FileId:
      name: fileId
      in: path
      required: true
      schema:
        type: string
      example: file_123
    PageSize:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    PageCursor:
      name: cursor
      in: query
      schema:
        type: string
        nullable: true
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      required: false
      schema:
        type: string
      description: Prevents duplicate creates on retries.

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
          example:
            code: BAD_REQUEST
            message: Invalid JSON payload
    Unauthorized:
      description: Missing/invalid authentication
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
          example:
            code: UNAUTHORIZED
            message: Invalid token
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
          example:
            code: NOT_FOUND
            message: Payment not found
    UnprocessableEntity:
      description: Semantic validation failed
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/Error"
              - type: object
                properties:
                  fieldErrors:
                    type: array
                    items:
                      $ref: "#/components/schemas/FieldError"
    ServerError:
      description: Server error
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }

  schemas:
    PaymentStatus:
      type: string
      enum: [requires_action, authorized, captured, succeeded, failed, canceled]

    Money:
      type: object
      required: [amount, currency]
      properties:
        amount:
          type: integer
          description: Minor units (e.g. cents)
          minimum: 1
        currency:
          type: string
          minLength: 3
          maxLength: 3

    Customer:
      type: object
      properties:
        id: { type: string }
        email:
          type: string
          format: email

    # Polymorphic payment method
    PaymentMethod:
      type: object
      required: [type]
      properties:
        type:
          type: string
          enum: [card, bank_transfer, wallet]
        card:
          $ref: "#/components/schemas/CardMethod"
        bankTransfer:
          $ref: "#/components/schemas/BankTransferMethod"
        wallet:
          $ref: "#/components/schemas/WalletMethod"
      discriminator:
        propertyName: type
        mapping:
          card: "#/components/schemas/CardMethod"
          bank_transfer: "#/components/schemas/BankTransferMethod"
          wallet: "#/components/schemas/WalletMethod"
      description: |
        Only the matching sub-object for the selected `type` should be provided.

    CardMethod:
      type: object
      required: [token]
      properties:
        token:
          type: string
          description: Tokenized card reference
          example: tok_test_visa_123

    BankTransferMethod:
      type: object
      required: [iban]
      properties:
        iban:
          type: string
          example: DE89370400440532013000

    WalletMethod:
      type: object
      required: [provider]
      properties:
        provider:
          type: string
          enum: [paypal, apple_pay, google_pay]

    CreatePaymentRequest:
      type: object
      required: [amount, currency, merchantReference, paymentMethod]
      properties:
        amount:
          type: integer
          minimum: 1
        currency:
          type: string
          minLength: 3
          maxLength: 3
        merchantReference:
          type: string
        paymentMethod:
          $ref: "#/components/schemas/PaymentMethod"
        customer:
          $ref: "#/components/schemas/Customer"
        returnUrl:
          type: string
          format: uri
        webhookUrl:
          type: string
          format: uri
          description: Used for callback demonstration
        metadata:
          type: object
          additionalProperties:
            type: string

    CreatePaymentForm:
      type: object
      required: [amount, currency, merchantReference]
      properties:
        amount: { type: integer }
        currency: { type: string }
        merchantReference: { type: string }

    PaymentBase:
      type: object
      required: [id, status, createdAt]
      properties:
        id:
          type: string
          example: pay_123
        status:
          $ref: "#/components/schemas/PaymentStatus"
        createdAt:
          type: string
          format: date-time

    Payment:
      allOf:
        - $ref: "#/components/schemas/PaymentBase"
        - type: object
          required: [amount, currency]
          properties:
            amount: { type: integer }
            currency: { type: string }
            customer: { $ref: "#/components/schemas/Customer" }
            # anyOf just to test rendering
            risk:
              anyOf:
                - type: object
                  properties:
                    score:
                      type: number
                      minimum: 0
                      maximum: 1
                - type: "null"

    PaginatedPayments:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Payment"
        nextCursor:
          type: string
          nullable: true

    FileUploadRequest:
      type: object
      required: [file]
      properties:
        file:
          type: string
          format: binary
        purpose:
          type: string
          enum: [kyc_document, dispute_evidence, generic]
        metadata:
          type: object
          additionalProperties:
            type: string

    FileObject:
      type: object
      required: [id, createdAt, size]
      properties:
        id: { type: string, example: file_123 }
        createdAt: { type: string, format: date-time }
        size: { type: integer, minimum: 0 }
        purpose: { type: string }
        checksum:
          type: string
          description: Example of format-ish field
        # self reference-ish via link type
        related:
          type: array
          items:
            $ref: "#/components/schemas/LinkRef"

    LinkRef:
      type: object
      required: [rel, href]
      properties:
        rel: { type: string, example: self }
        href: { type: string, format: uri }

    WebhookEvent:
      type: object
      required: [id, type, createdAt, data]
      properties:
        id: { type: string, example: evt_123 }
        type:
          type: string
          enum: [payment.created, payment.updated, payment.failed]
        createdAt: { type: string, format: date-time }
        data:
          type: object
          required: [payment]
          properties:
            payment:
              $ref: "#/components/schemas/Payment"

    FieldError:
      type: object
      required: [field, message]
      properties:
        field: { type: string, example: amount }
        message: { type: string, example: Must be >= 1 }

    Error:
      type: object
      required: [code, message]
      properties:
        code: { type: string }
        message: { type: string }
        traceId:
          type: string
          description: Correlates with server logs
